# -*- coding: utf-8 -*-
"""day 2 fdp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1akmS_nuSvzqijLzGQuqqKhYNFjBOhBSU
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm

# Generate x values
x = np.linspace(-5, 5, 100)

# Generate normal distribution values
y = norm.pdf(x, 0, 1)

# Plot bell-shaped curve
plt.plot(x, y)

# Add title and labels
plt.title("Bell-Shaped Curve (Normal Distribution)")
plt.xlabel("X Values")
plt.ylabel("Probability Density")

# Display graph
plt.show()

